export const WORK_PERMIT_BOT_DATA_SOURCE = 'WORK_PERMIT_BOT_DATA_SOURCE';

export const MODELS = {
  USER_MODEL: 'USER_MODEL',
  REQUEST_MODEL: 'REQUEST_MODEL',
  ATTENDANCE_MODEL: 'ATTENDANCE_MODEL',
};
