export const WORK_PERMIT_BOT_DATA_SOURCE = 'WORK_PERMIT_BOT_DATA_SOURCE';

export const MODELS = {
  MANAGER_MODEL: 'MANAGER_MODEL',
  REQUEST_MODEL: 'REQUEST_MODEL',
  WORKERS_MODEL: 'WORKERS_MODEL',
  ATTENDANCE_MODEL: 'ATTENDANCE_MODEL',
};
