name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Build
        run: npm run build

      - name: Test
        run: npm test --if-present

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  docker-image:
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: workpermit-bot
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/workpermit-bot:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    needs: docker-image
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Debug secrets format
        run: |
          echo "DEPLOY_HOST length: ${#DEPLOY_HOST}"
          echo "DEPLOY_USER length: ${#DEPLOY_USER}" 
          echo "DEPLOY_HOST first 10 chars: '${DEPLOY_HOST:0:10}'"
          echo "DEPLOY_USER first 10 chars: '${DEPLOY_USER:0:10}'"
          echo "DEPLOY_HOST last 5 chars: '...${DEPLOY_HOST: -5}'"
          echo "Raw connection string would be: ${DEPLOY_USER}@${DEPLOY_HOST}"
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}

      - name: Known hosts
        run: |
          mkdir -p ~/.ssh
          # Try to get host key, fallback to StrictHostKeyChecking=no
          ssh-keyscan -T 10 -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts 2>/dev/null || echo "Using StrictHostKeyChecking=no"
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}

      - name: Deploy via SSH
        run: |
          echo "Connecting to: $DEPLOY_USER@$DEPLOY_HOST"
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$DEPLOY_USER@$DEPLOY_HOST" <<'EOF'
          set -e
          echo "Pulling latest image..."
          docker pull ghcr.io/${{ github.repository_owner }}/workpermit-bot:latest
          mkdir -p /srv/workpermit
          cd /srv/workpermit
          cat > docker-compose.yml <<'YML'
          version: '3.8'
          services:
            app:
              image: ghcr.io/${{ github.repository_owner }}/workpermit-bot:latest
              restart: unless-stopped
              environment:
                NODE_ENV: production
                DB_HOST: ${DB_HOST}
                DB_PORT: ${DB_PORT}
                DB_NAME: ${DB_NAME}
                DB_USER: ${DB_USER}
                DB_PASSWORD: ${DB_PASSWORD}
                DB_SCHEMA: ${DB_SCHEMA}
                BOT_TOKEN: ${BOT_TOKEN}
              ports:
                - "3000:3000"
          YML
          docker compose up -d
          EOF
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}

      - name: Post deploy check
        run: echo "Deployment triggered."
